module.exports = namesArray = [
  "John",
  "Alice",
  "Bob",
  "Eva",
  "Michael",
  "Sophia",
  "Daniel",
  "Olivia",
  "Matthew",
  "Ava",
  "William",
  "Emma",
  "Alexander",
  "Isabella",
  "James",
  "Mia",
  "Benjamin",
  "Abigail",
  "David",
  "Emily",
  "Joseph",
  "Charlotte",
  "Christopher",
  "Amelia",
  "Andrew",
  "Harper",
  "Nathan",
  "Evelyn",
  "Samuel",
  "Ella",
  "Nicholas",
  "Grace",
  "Jacob",
  "Avery",
  "Logan",
  "Scarlett",
  "Ryan",
  "Chloe",
  "Christian",
  "Victoria",
  "Gabriel",
  "Aria",
  "Jonathan",
  "Liam",
  "Lillian",
  "Anthony",
  "Madison",
  "Dylan",
  "Sofia",
  "Brandon",
  "Addison",
  "Caleb",
  "Aubrey",
  "Ethan",
  "Layla",
  "Isaac",
  "Hannah",
  "Owen",
  "Natalie",
  "Luke",
  "Zoe",
  "Isaiah",
  "Brooklyn",
  "Henry",
  "Audrey",
  "Jackson",
  "Leah",
  "Wyatt",
  "Stella",
  "Elijah",
  "Peyton",
  "Julian",
  "Nora",
  "Cameron",
  "Lucy",
  "Isabel",
  "Austin",
  "Ellie",
  "Leo",
  "Claire",
  "Hunter",
  "Skylar",
  "Adam",
  "Maya",
  "Jayden",
  "Anna",
  "Evan",
  "Lily",
  "Mason",
  "Katherine",
  "Jack",
  "Bella",
  "Carter",
  "Aaliyah",
  "Jaden",
  "Gabriella",
  "Tyler",
  "Alexa",
  "Eli",
  "Ariana",
  "Nathaniel",
  "Mila",
  "Sebastian",
  "Paisley",
  "Colton",
  "Hazel",
  "Kevin",
  "Kylie",
  "Zachary",
  "Ellie",
  "Xavier",
  "Taylor",
  "Cooper",
  "Kaylee",
  "Levi",
  "Luna",
  "Carson",
  "Lydia",
  "Brayden",
  "Gianna",
  "Dominic",
  "Liliana",
  "Josiah",
  "Aubree",
  "Vincent",
  "Savannah",
  "Parker",
  "Zara",
  "Johnathan",
  "Aurora",
  "Chase",
  "Holly",
  "Roman",
  "Brianna",
  "Alex",
  "Penelope",
  "Jason",
  "Allison",
  "Aaron",
  "Layla",
  "Charles",
  "Alyssa",
  "Grayson",
  "Violet",
  "Colin",
  "Ruby",
  "Ezra",
  "Clara",
  "Thomas",
  "Samantha",
  "Jace",
  "Elena",
  "Xander",
  "Alexis",
  "Landon",
  "Nevaeh",
  "Adrian",
  "Gabrielle",
  "Connor",
  "Mackenzie",
  "Jordan",
  "Sadie",
  "Leighton",
  "Riley",
  "Xavi",
  "Piper",
  "Oscar",
  "Delilah",
  "Finn",
  "Aubrey",
  "Miles",
  "Ariel",
  "Silas",
  "Emma",
  // ... Add more names as needed
];

// function shuffleArrays(arr1, arr2) {
//     if (arr1.length !== arr2.length) {
//         throw new Error("Arrays must be of the same length");
//     }

//     for (let i = arr1.length - 1; i > 0; i--) {
//         const j = Math.floor(Math.random() * (i + 1));

//         // Swap elements between the two arrays
//         [arr1[i], arr1[j]] = [arr1[j], arr1[i]];
//         [arr2[i], arr2[j]] = [arr2[j], arr2[i]];
//     }
// }

// module.exports=namesArray=shuffleArrays(Names,name_fem)
var cities = [
  "New York",
  "London",
  "Tokyo",
  "Paris",
  "Berlin",
  "Sydney",
  "Rio de Janeiro",
  "Cairo",
  "Mumbai",
  "Beijing",
  "Moscow",
  "Toronto",
  "Rome",
  "Dubai",
  "Cape Town",
  "Lima",
  "Bangkok",
  "Seoul",
  "Mexico City",
  "Los Angeles",
  "Buenos Aires",
  "Istanbul",
  "Jakarta",
  "Nairobi",
  "Toronto",
  "Vancouver",
  "Athens",
  "Auckland",
  "Copenhagen",
  "Stockholm",
  "Oslo",
  "Hanoi",
  "Wellington",
  "Dublin",
  "Amsterdam",
  "Warsaw",
  "Prague",
  "Budapest",
  "Vienna",
  "Brussels",
  "Madrid",
  "Barcelona",
  "Lisbon",
  "Zurich",
  "Geneva",
  "Copenhagen",
  "Munich",
  "Helsinki",
  "Edinburgh",
  "Reykjavik",
  "Brasília",
  "Caracas",
  "Panama City",
  "Lisbon",
  "Stockholm",
  "Bucharest",
  "Belgrade",
  "Helsinki",
  "Oslo",
  "Warsaw",
  "Budapest",
  "Prague",
  "Sofia",
  "Bratislava",
  "Ljubljana",
  "Zagreb",
  "Athens",
  "Nicosia",
  "Riyadh",
  "Doha",
  "Kuwait City",
  "Manama",
  "Muscat",
  "Abu Dhabi",
  "Jerusalem",
  "Tel Aviv",
  "Baghdad",
  "Tehran",
  "Riyadh",
  "Kuwait City",
  "Doha",
  "Manila",
  "Hanoi",
  "Bangkok",
  "Phnom Penh",
  "Vientiane",
  "Yangon",
  "Kuala Lumpur",
  "Singapore",
  "Jakarta",
  "Bandar Seri Begawan",
  "Hanoi",
  "Naypyidaw",
  "Phnom Penh",
  "Manila",
  "Bangkok",
  "Vientiane",
  "Bandar Seri Begawan",
  "Kuala Lumpur",
  "Yangon",
  "Singapore",
  "Canberra",
  "Wellington",
  "Suva",
  "Apia",
  "Honolulu",
  "Papeete",
  "Alofi",
  "Nuku'alofa",
  "Port Moresby",
  "Honiara",
  "Port Vila",
  "Tarawa",
  "Majuro",
  "Palikir",
  "Yaren",
  "Mata-Utu",
  "Funafuti",
  "South Tarawa",
  "Palikir",
  "Majuro",
  "Port Moresby",
  "Honiara",
  "Port Vila",
  "Apia",
  "Suva",
  "Wellington",
  "Canberra",
  "Mata-Utu",
  "Funafuti",
  "Alofi",
  "Nuku'alofa",
  "Papeete",
  "Honolulu",
  "Beirut",
  "Amman",
  "Damascus",
  "Baghdad",
  "Kuwait City",
  "Manama",
  "Muscat",
  "Sanaa",
  "Riyadh",
  "Doha",
  "Abu Dhabi",
  "Tehran",
  "Jerusalem",
  "Tel Aviv",
  "Ankara",
  "Baku",
  "Yerevan",
  "Tbilisi",
  "Bishkek",
  "Dushanbe",
  "Ashgabat",
  "Nur-Sultan",
  "Tashkent",
  "Baku",
  "Yerevan",
  "Tbilisi",
  "Bishkek",
  "Dushanbe",
  "Ashgabat",
  "Nur-Sultan",
  "Tashkent",
  "Tirana",
  "Andorra la Vella",
  "Yerevan",
  "Vienna",
  "Baku",
  "Minsk",
  "Brussels",
  "Sarajevo",
  "Sofia",
  "Zagreb",
  "Nicosia",
  "Prague",
  "Copenhagen",
  "Tallinn",
  "Helsinki",
  "Paris",
  "Tbilisi",
  "Berlin",
  "Athens",
  "Budapest",
  "Reykjavik",
  "Dublin",
  "Rome",
  "Astana",
  "Prishtina",
  "Riga",
  "Vaduz",
  "Vilnius",
  "Luxembourg",
  "Skopje",
  "Valletta",
  "Chisinau",
  "Monaco",
  "Podgorica",
  "Amsterdam",
  "Oslo",
  "Warsaw",
  "Lisbon",
  "Bucharest",
  "Moscow",
  "San Marino",
  "Belgrade",
  "Bratislava",
  "Ljubljana",
  "Madrid",
  "Stockholm",
  "Bern",
  "Ankara",
  "Kyiv",
  "London",
  "Vatican City",
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Jacksonville",
  "San Francisco",
  "Indianapolis",
  "Columbus",
  "Fort Worth",
  "Charlotte",
  "Seattle",
  "Denver",
  "Washington",
  "Boston",
  "El Paso",
  "Detroit",
  "Nashville",
  "Memphis",
  "Portland",
  "Oklahoma City",
  "Las Vegas",
  "Louisville",
  "Baltimore",
  "Milwaukee",
  "Albuquerque",
  "Tucson",
  "Fresno",
  "Sacramento",
  "Mesa",
  "Kansas City",
  "Atlanta",
  "Long Beach",
  "Colorado Springs",
  "Raleigh",
  "Miami",
  "Oakland",
  "Minneapolis",
  "Tulsa",
  "Cleveland",
  "Wichita",
  "Arlington",
  "New Orleans",
  "Bakersfield",
  "Tampa",
  "Aurora",
  "Honolulu",
  "Anaheim",
  "Santa Ana",
  "St. Louis",
  "Riverside",
  "Corpus Christi",
  "Pittsburgh",
  "Lexington",
  "Anchorage",
  "Stockton",
  "Cincinnati",
  "St. Paul",
  "Toledo",
  "Newark",
  "Greensboro",
  "Plano",
  "Henderson",
  "Lincoln",
  "Buffalo",
  "Fort Wayne",
  "Jersey City",
  "Chula Vista",
  "Orlando",
  "St. Petersburg",
  "Norfolk",
  "Chandler",
  "Laredo",
  "Madison",
  "Durham",
  "Lubbock",
  "Winston-Salem",
  "Garland",
  "Glendale",
  "Hialeah",
  "Reno",
  "Baton Rouge",
  "Irvine",
  "Chesapeake",
  "Irving",
  "Scottsdale",
  "North Las Vegas",
  "Fremont",
  "Gilbert",
  "San Bernardino",
  "Boise",
  "Birmingham",
  "Rochester",
  "Richmond",
  "Spokane",
  "Des Moines",
  "Montgomery",
  "Modesto",
  "Fayetteville",
  "Tacoma",
  "Shreveport",
  "Fontana",
  "Oxnard",
  "Aurora",
  "Moreno Valley",
  "Akron",
  "Yonkers",
  "Columbus",
  "Augusta",
  "Little Rock",
  "Amarillo",
  "Mobile",
  "Huntington Beach",
  "Glendale",
  "Grand Rapids",
  "Salt Lake City",
  "Tallahassee",
  "Huntsville",
  "Worcester",
  "Knoxville",
  "Grand Prairie",
  "Newport News",
  "Brownsville",
  "Santa Clarita",
  "Overland Park",
  "Providence",
  "Garden Grove",
  "Chattanooga",
  "Oceanside",
  "Jackson",
  "Fort Lauderdale",
  "Santa Rosa",
  "Rancho Cucamonga",
  "Port St. Lucie",
  "Tempe",
  "Ontario",
  "Vancouver",
  "Sioux Falls",
  "Springfield",
  "Pembroke Pines",
  "Salem",
  "Cape Coral",
  "Peoria",
  "Sioux Falls",
  "Springfield",
  "Pembroke Pines",
  "Salem",
  "Cape Coral",
  "Peoria",
  "Lancaster",
  "Elk Grove",
  "Corona",
  "Eugene",
  "Palmdale",
  "Salinas",
  "Springfield",
  "Pasadena",
  "Fort Collins",
  "Hayward",
  "Pomona",
  "Cary",
  "Rockford",
  "Alexandria",
  "Escondido",
  "McKinney",
  "Killeen",
  "Bridgeport",
  "Savannah",
  "Syracuse",
  "Naperville",
  "Mesquite",
  "Pasadena",
  "Orange",
  "Fullerton",
  "Dayton",
  "Miramar",
  "Thornton",
  "Waco",
  "Murrieta",
  "West Valley City",
  "Topeka",
  "Thousand Oaks",
  "Cedar Rapids",
  "Olathe",
  "Hampton",
  "Visalia",
  "Gainesville",
  "Simi Valley",
  "Sterling Heights",
  "New Haven",
  "Columbia",
  "Concord",
  "Kent",
  "Santa Clara",
  "Elizabeth",
  "Round Rock",
  "Thousand Oaks",
  "Cedar Rapids",
  "Olathe",
  "Hampton",
  "Visalia",
  "Gainesville",
  "Simi Valley",
  "Sterling Heights",
  "New Haven",
  "Columbia",
  "Concord",
  "Kent",
  "Santa Clara",
  "Elizabeth",
  "Round Rock",
  "Torrance",
  "Sterling Heights",
  "Richmond",
  "Berkeley",
  "Columbia",
  "Allentown",
  "Evansville",
  "Abilene",
  "Frisco",
  "Clermont-Ferrand",
  "Dnipro",
  "Rotterdam",
  "Saratov",
  "Volgograd",
  "Odessa",
  "Omsk",
  "Voronezh",
  "Krasnoyarsk",
  "Samara",
  "Nizhny Novgorod",
  "Chelyabinsk",
  "Yekaterinburg",
  "Novosibirsk",
  "Ufa",
  "Kazan",
  "Perm",
  "Rostov-on-Don",
  "Saint Petersburg",
  "Moscow",
  "Kiev",
  "Minsk",
  "Khabarovsk",
  "Vladivostok",
  "Yakutsk",
  "Irkutsk",
  "Novokuznetsk",
  "Tomsk",
  "Krasnodar",
  "Sochi",
  "Taganrog",
  "Astrakhan",
  "Stavropol",
  "Grozny",
  "Magadan",
  "Petropavlovsk-Kamchatsky",
  "Anadyr",
  "Yuzhno-Sakhalinsk",
  "Yerevan",
  "Baku",
  "Tbilisi",
  "Almaty",
  "Nur-Sultan",
  "Bishkek",
  "Dushanbe",
  "Ashgabat",
  "Tashkent",
  "Tirana",
  "Andorra la Vella",
  "Vienna",
  "Minsk",
  "Brussels",
  "Sarajevo",
  "Sofia",
  "Zagreb",
  "Nicosia",
  "Prague",
  "Copenhagen",
  "Tallinn",
  "Helsinki",
  "Paris",
  "Tbilisi",
  "Berlin",
  "Athens",
  "Budapest",
  "Reykjavik",
  "Dublin",
  "Rome",
  "Astana",
  "Prishtina",
  "Riga",
  "Vaduz",
  "Vilnius",
  "Luxembourg",
  "Skopje",
  "Valletta",
  "Chisinau",
  "Monaco",
  "Podgorica",
  "Amsterdam",
  "Oslo",
  "Warsaw",
  "Lisbon",
  "Bucharest",
  "Moscow",
  "San Marino",
  "Belgrade",
  "Bratislava",
  "Ljubljana",
  "Madrid",
  "Stockholm",
  "Bern",
  "Ankara",
  "Kyiv",
  "London",
];

citiesArrays = cities.filter((item, index) => cities.indexOf(item) === index);

const countries = [
  "Zimbabwe",
  "Tajikistan",
  "South Sudan",
  "Peru",
  "Norway",
  "Equatorial Guinea",
  "Belgium",
  "Grenada",
  "Niger",
  "Singapore",
  "Argentina",
  "Burundi",
  "Central African Republic",
  "Latvia",
  "Bhutan",
  "Cambodia",
  "Marshall Islands",
  "Mongolia",
  "United States",
  "Mozambique",
  "Comoros",
  "Fiji",
  "Netherlands",
  "Panama",
  "Serbia",
  "Iraq",
  "El Salvador",
  "Guatemala",
  "Dominican Republic",
  "Kenya",
  "Oman",
  "Nigeria",
  "Turkey",
  "Uruguay",
  "Rwanda",
  "Bosnia and Herzegovina",
  "Madagascar",
  "Guyana",
  "Kuwait",
  "Congo",
  "Tunisia",
  "Liberia",
  "Seychelles",
  "Thailand",
  "Cyprus",
  "Morocco",
  "Myanmar",
  "Kyrgyzstan",
  "Samoa",
  "Antigua and Barbuda",
  "Honduras",
  "Malaysia",
  "Kosovo",
  "Belarus",
  "Algeria",
  "Bangladesh",
  "Indonesia",
  "Latvia",
  "Guinea-Bissau",
  "Qatar",
  "Italy",
  "Bulgaria",
  "Slovenia",
  "Saint Lucia",
  "Albania",
  "Australia",
  "Lesotho",
  "Cameroon",
  "Saint Vincent and the Grenadines",
  "Haiti",
  "Ecuador",
  "Mali",
  "Senegal",
  "Jordan",
  "Chile",
  "Portugal",
  "Sao Tome and Principe",
  "Nepal",
  "South Africa",
  "Malta",
  "Armenia",
  "Austria",
  "Micronesia",
  "Kazakhstan",
  "Vanuatu",
  "Benin",
  "Israel",
  "Jamaica",
  "Tonga",
  "Turkmenistan",
  "Moldova",
  "North Macedonia",
  "Saudi Arabia",
  "Sweden",
  "Denmark",
  "Dominica",
  "India",
  "Greece",
  "New Zealand",
  "Bahrain",
  "Palau",
  "Nicaragua",
  "Palau",
  "Vietnam",
  "Eritrea",
  "Kiribati",
  "Solomon Islands",
  "Ukraine",
  "Belize",
  "Maldives",
  "Azerbaijan",
  "Czech Republic",
  "Finland",
  "Gambia",
  "Chad",
  "Uzbekistan",
  "France",
  "Trinidad and Tobago",
  "Paraguay",
  "Saint Kitts and Nevis",
  "Egypt",
  "Syria",
  "Bolivia",
  "Yemen",
  "Iceland",
  "Lebanon",
  "Sierra Leone",
  "Sudan",
  "Nauru",
  "Albania",
  "Saudi Arabia",
  "Germany",
  "Saint Vincent and the Grenadines",
  "Mauritania",
  "Azerbaijan",
  "Turkmenistan",
  "Slovakia",
  "Morocco",
  "Nicaragua",
  "Maldives",
  "Serbia",
  "Cape Verde",
  "Qatar",
  "Belize",
  "Ireland",
  "Iraq",
  "Moldova",
  "Greece",
  "Rwanda",
  "France",
  "Burundi",
  "Trinidad and Tobago",
  "Algeria",
  "Nauru",
  "Lesotho",
  "Kuwait",
  "Vietnam",
  "Bhutan",
  "United Kingdom",
  "Mongolia",
  "Togo",
  "Philippines",
  "Panama",
  "Liberia",
  "Cuba",
  "Angola",
  "Afghanistan",
  "Slovenia",
  "Bangladesh",
  "Mauritius",
  "United Arab Emirates",
  "Nigeria",
  "Hungary",
];

const lastNames = [
  "Smith",
  "Johnson",
  "Williams",
  "Jones",
  "Brown",
  "Davis",
  "Miller",
  "Wilson",
  "Moore",
  "Taylor",
  "Anderson",
  "Thomas",
  "Jackson",
  "White",
  "Harris",
  "Martin",
  "Thompson",
  "Garcia",
  "Martinez",
  "Robinson",
  "Clark",
  "Rodriguez",
  "Lewis",
  "Lee",
  "Walker",
  "Hall",
  "Allen",
  "Young",
  "Hernandez",
  "King",
  "Wright",
  "Lopez",
  "Hill",
  "Scott",
  "Green",
  "Adams",
  "Baker",
  "Gonzalez",
  "Nelson",
  "Carter",
  "Mitchell",
  "Perez",
  "Roberts",
  "Turner",
  "Phillips",
  "Campbell",
  "Parker",
  "Evans",
  "Edwards",
  "Collins",
  "Stewart",
  "Sanchez",
  "Morris",
  "Rogers",
  "Reed",
  "Cook",
  "Morgan",
  "Bell",
  "Murphy",
  "Bailey",
  "Rivera",
  "Cooper",
  "Richardson",
  "Cox",
  "Howard",
  "Ward",
  "Torres",
  "Peterson",
  "Gray",
  "Ramirez",
  "James",
  "Watson",
  "Brooks",
  "Kelly",
  "Sanders",
  "Price",
  "Bennett",
  "Wood",
  "Barnes",
  "Ross",
  "Henderson",
  "Coleman",
  "Jenkins",
  "Perry",
  "Powell",
  "Long",
  "Patterson",
  "Hughes",
  "Flores",
  "Washington",
  "Butler",
  "Simmons",
  "Foster",
  "Gonzales",
  "Bryant",
  "Alexander",
  "Russell",
  "Griffin",
  "Diaz",
  "Hayes",
  "Myers",
  "Ford",
  "Hamilton",
  "Graham",
  "Sullivan",
  "Wallace",
  "Woods",
  "Cole",
  "West",
  "Jordan",
  "Owens",
  "Reynolds",
  "Fisher",
  "Ellis",
  "Harrison",
  "Gibson",
  "Mcdonald",
  "Cruz",
  "Marshall",
  "Ortiz",
  "Gomez",
  "Murray",
  "Freeman",
  "Wells",
  "Webb",
  "Simpson",
  "Stevens",
  "Tucker",
  "Porter",
  "Hunter",
  "Hicks",
  "Crawford",
  "Henry",
  "Boyd",
  "Mason",
  "Morales",
  "Kennedy",
  "Warren",
  "Dixon",
  "Ramos",
  "Reyes",
  "Burns",
  "Gordon",
  "Shaw",
  "Holmes",
  "Rice",
  "Robertson",
  "Hunt",
  "Black",
  "Daniels",
  "Palmer",
  "Mills",
  "Nichols",
  "Grant",
  "Knight",
  "Ferguson",
  "Rose",
  "Stone",
  "Hawkins",
  "Dunn",
];

const jobs = [
  "Software Engineer",
  "Data Scientist",
  "Graphic Designer",
  "Marketing Specialist",
  "Financial Analyst",
  "Human Resources Manager",
  "Product Manager",
  "Customer Support Representative",
  "Sales Manager",
  "Business Analyst",
  "Content Writer",
  "UX/UI Designer",
  "Project Manager",
  "Systems Administrator",
  "Network Engineer",
  "Social Media Manager",
  "Digital Marketing Manager",
  "Accountant",
  "Operations Manager",
  "IT Consultant",
  "Web Developer",
  "Quality Assurance Analyst",
  "Research Analyst",
  "Legal Counsel",
  "Logistics Coordinator",
  "Event Planner",
  "Executive Assistant",
  "Public Relations Specialist",
  "Healthcare Administrator",
  "Teacher",
  "Nurse",
  "Architect",
  "Mechanical Engineer",
  "Electrician",
  "Plumber",
  "Construction Project Manager",
  "Chef",
  "Barista",
  "Fitness Trainer",
  "Interior Designer",
  "Photographer",
  "Police Officer",
  "Firefighter",
  "Paramedic",
  "Pilot",
  "Flight Attendant",
  "Journalist",
  "Librarian",
  "Real Estate Agent",
  "Social Worker",
  "Psychologist",
  "Counselor",
  "Pharmacist",
  "Veterinarian",
  "Biomedical Scientist",
  "Environmental Engineer",
  "Research Scientist",
  "Biotech Analyst",
  "Geologist",
  "Meteorologist",
  "Astronomer",
  "Fashion Designer",
  "Retail Manager",
  "Stock Trader",
  "Actuary",
  "Translator",
  "Electrician",
  "IT Support Specialist",
  "Cryptocurrency Analyst",
  "Blockchain Developer",
  "Ethical Hacker",
  "GIS Specialist",
  "Solar Energy Consultant",
  "Marine Biologist",
  "Robotics Engineer",
  "Virtual Reality Developer",
  "Dental Hygienist",
  "Phlebotomist",
  "Fitness Instructor",
  "Social Media Influencer",
  "Podcast Producer",
  "Gaming Developer",
  "Forensic Scientist",
  "Ethnobotanist",
  "Zoologist",
  "Neuroscientist",
  "Biomedical Engineer",
  "Epidemiologist",
  "Medical Illustrator",
  "Forestry Technician",
  "Sustainability Consultant",
  "Bioinformatician",
  "Machine Learning Engineer",
];
const productsArray = [
  "Blue T-shirt",
  "Coffee Mug",
  "Notebook",
  "Wireless Mouse",
  "Sunglasses",
  "Laptop Stand",
  "Canvas Backpack",
  "Stainless Steel Water Bottle",
  "Desk Organizer",
  "Cotton Socks",
  "Running Shoes",
  "Phone Holder",
  "Smartphone Case",
  "USB Flash Drive",
  "Whiteboard Markers",
  "Desk Lamp",
  "Pocket Umbrella",
  "Leather Wallet",
  "Travel Pillow",
  "Insulated Lunch Box",
  "Stainless Steel Travel Mug",
  "Yoga Mat",
  "Resistance Bands",
  "Bluetooth Earphones",
  "Wireless Charger",
  "Portable Speaker",
  "Beach Towel",
  "Graphic Novel",
  "Ceramic Plant Pot",
  "Puzzle Game",
  "Crossbody Bag",
  "Sleep Mask",
  "Aromatherapy Diffuser",
  "Fitness Tracker",
  "Dumbbell Set",
  "Camping Lantern",
  "Reusable Grocery Bags",
  "Hair Dryer",
  "Facial Cleanser",
  "Cooking Utensil Set",
  "Bike Lock",
  "Spiral-bound Sketchbook",
  "Sports Water Bottle",
  "Jigsaw Puzzle",
  "Reusable Silicone Food Bags",
  "Portable Fan",
  "Travel Adapter",
  "Hiking Boots",
  "Foldable Camping Chair",
  "Coloring Book",
  "Power Bank",
  "Microfiber Towel",
  "Pedometer",
  "Screen Protector",
  "Foldable Bluetooth Keyboard",
  "Camping Cookware Set",
  "Sleeping Bag",
  "Hand Sanitizer",
  "Sunscreen",
  "Reading Glasses",
  "Plastic Hangers",
  "Adjustable Wrench",
  "Rain Poncho",
  "Insulated Wine Tumbler",
  "Car Phone Mount",
  "Stainless Steel Straw Set",
  "Wooden Clothespins",
  "Shower Caddy",
  "Magnetic Whiteboard",
  "Reusable Coffee Filter",
  "LED Flashlight",
  "Colorful Markers",
  "Travel Toiletry Kit",
  "Kettlebell",
  "Rolling Duffel Bag",
  "Outdoor Blanket",
  "Tea Infuser",
  "Portable Ice Maker",
  "Smart Home Plug",
  "Vegetable Spiralizer",
  "Ceramic Coasters",
  "Digital Meat Thermometer",
  "Yoga Block",
  "Collapsible Water Bowl",
  "Carabiner Clip",
  "Puzzle Mat",
  "Luggage Scale",
  "Camping Hammock",
  "Foldable Sun Hat",
  "Bamboo Toothbrush Set",
  "Hiking Pole",
  "Hand Warmer",
  "Bluetooth FM Transmitter",
  "Portable Charcoal Grill",
  "Waterproof Dry Bag",
  "Silicone Baking Mat",
  "Travel Laundry Bag",
  "Rechargeable Hand Warmer",
  "Collapsible Water Bottle",
  "Inflatable Neck Pillow",
  "Car Trash Can",
  "Portable Espresso Maker",
  "Cord Organizer",
  "Reusable Stainless Steel Straw",
  "Camping Stove",
  "Silicone Food Storage Bags",
  "Fitness Dice",
  "LED Book Light",
  "Stainless Steel Mixing Bowls",
  "Glow-in-the-dark Stars Stickers",
  "Portable BBQ Grill",
  "Travel Neck Wallet",
  "Multi-Tool",
  "Camping Tent",
  "Adjustable Laptop Stand",
  "Puzzle Cube",
  "Magnetic Cable Organizer",
  "Sleeping Mask with Earplugs",
  "Resistance Loop Bands",
  "Collapsible Food Container",
  "Camping Cot",
  "Mini First Aid Kit",
  "Camping Headlamp",
  "Retractable Clothesline",
  "Foam Roller",
  "Foldable Solar Charger",
  "Reusable Beeswax Wraps",
  "Camping Coffee Maker",
  "Bike Repair Kit",
  "Pocket Multi-Tool",
  "Outdoor Portable Table",
  "Basic T-Shirt",
  "Cotton Socks",
  "Stainless Steel Water Bottle",
  "Wooden Desk Organizer",
  "LED Desk Lamp",
  "Notebook Set",
  "Canvas Backpack",
  "Wireless Mouse",
  "Coffee Mug",
  "Pocket Umbrella",
  "Bluetooth Earphones",
  "Portable Power Bank",
  "Glass Water Pitcher",
  "Non-Stick Frying Pan",
  "Yoga Mat",
  "Travel Pillow",
  "Leather Wallet",
  "Sunglasses",
  "Desk Chair",
  "Ceramic Plant Pot",
  "Hiking Backpack",
  "Digital Alarm Clock",
  "Stainless Steel Travel Mug",
  "Fitness Tracker",
  "USB Flash Drive",
  "Smartphone Stand",
  "Reusable Shopping Bag",
  "Stainless Steel Cutlery Set",
  "Gaming Mousepad",
  "Hair Dryer",
  "Cotton Pillowcase Set",
  "Resistance Bands Set",
  "Kitchen Timer",
  "Wall Clock",
  "Bamboo Toothbrush Set",
  "Garden Gloves",
  "HDMI Cable",
  "Cooking Apron",
  "Laptop Stand",
  "Running Shoes",
  "Microfiber Cleaning Cloths",
  "Insulated Lunch Box",
  "Cotton Towel Set",
  "Bluetooth Speaker",
  "Running Belt",
  "Sleeping Mask",
  "Silicone Baking Mat",
  "Wireless Charger",
  "Stainless Steel Mixing Bowls",
  "Tea Infuser",
  "Elastic Shoe Laces",
  "Handheld Fan",
  "Reusable Ice Cubes",
  "Sunscreen Lotion",
  "Foldable Backpack",
  "Bike Water Bottle Holder",
  "Fitness Foam Roller",
  "Gel Ink Pens Set",
  "Car Phone Holder",
  "Hand Sanitizer Gel",
  "Gourmet Coffee Beans",
  "Adjustable Laptop Desk",
  "Desk Organizer Set",
  "Stainless Steel Straw Set",
  "LED String Lights",
  "Faux Leather Journal",
  "Electric Kettle",
  "Bicycle Repair Tool Kit",
  "Portable Bluetooth Keyboard",
  "Soy Wax Candles Set",
  "Metallic Watercolor Paint Set",
  "Hiking Trail Mix",
  "Puzzle Board Game",
  "Hydration Backpack",
  "Non-Slip Yoga Mat",
  "Resistance Loop Bands",
  "USB-C Hub",
  "Artificial Succulent Plants",
  "Glass Spice Jars Set",
  "Reusable Silicone Food Storage Bags",
  "Inflatable Travel Neck Pillow",
  "Camping Cookware Set",
  "Cotton Oven Mitts",
  "Collapsible Water Bottle",
  "Silicone Food Huggers Set",
  "Portable Espresso Maker",
  "Miniature Desk Plant",
  "Wooden Clothes Hangers Set",
  "Aromatherapy Essential Oils Set",
  "Foldable Laundry Basket",
  "Insulated Wine Tumbler",
  "Ceramic Coasters Set",
  "USB Desk Fan",
  "Cotton Face Masks Set",
];
const streets = [
    'Broadway',
    'Main Street',
    'Park Avenue',
    'Elm Street',
    'Maple Avenue',
    'Washington Street',
    'Market Street',
    'State Street',
    'Madison Avenue',
    'Oak Street',
    'Pine Street',
    'Cedar Avenue',
    'Chestnut Street',
    'Fifth Avenue',
    'Spring Street',
    'High Street',
    'Central Avenue',
    'Church Street',
    'Pearl Street',
    'Jefferson Street',
    'First Street',
    'Front Street',
    'Water Street',
    'Canal Street',
    'Eighth Avenue',
    'Franklin Street',
    'Ninth Street',
    'Second Street',
    'Hill Street',
    'Tenth Street',
    'Union Street',
    'Cherry Street',
    'Willow Street',
    'Ninth Avenue',
    'School Street',
    'Park Place',
    'Railroad Avenue',
    'Lake Street',
    'Pleasant Street',
    'Meadow Lane',
    'Grove Street',
    'River Road',
    'Linden Street',
    'Beech Street',
    'Hickory Lane',
    'Sunset Drive',
    'Eagle Street',
    'Bridge Street',
    'Mill Street',
    'Forest Avenue',
    'Broad Street',
    'West Street',
    'Hillcrest Drive',
    'Birch Street',
    'Prospect Street',
    'Locust Street',
    'Cottage Lane',
    'Valley Road',
    'Summit Avenue',
    'York Street',
    'Pleasant Avenue',
    'Cambridge Road',
    'Euclid Avenue',
    'Orchard Street',
    'Crescent Street',
    'Harrison Street',
    'Columbia Street',
    'Berkshire Drive',
    'Glenwood Avenue',
    'Poplar Street',
    'Ridge Road',
    'Sherman Street',
    'Heather Lane',
    'Morgan Street',
    'Westminster Drive',
    'Pennsylvania Avenue',
    'Magnolia Avenue',
    'Essex Court',
    'Acorn Lane',
    'Holly Court',
    'Colonial Drive',
    'Parkview Drive',
    'Willow Drive',
    'Lakeview Drive',
    'Cypress Court',
    'Meadow Lane',
    'Maple Court',
    'Spruce Street',
    'Oxford Court',
    'Pine Court',
    'Hillside Drive',
    'Valley Drive',
    'Chestnut Court',
    'Pinecrest Drive',
    'Edgewood Avenue',
    'Hawthorn Court',
    'Aspen Court',
    'Brookside Drive',
    'Heritage Drive',
    'Dogwood Court',
    'Main Street',
    'Broadway',
    'Park Avenue',
    'High Street',
    'Abbey Road',
    'Fifth Avenue',
    'Bourbon Street',
    'Sunset Boulevard',
    'Oxford Street',
    'Rodeo Drive',
    'Wall Street',
    'Champs-Élysées',
    'Lombard Street',
    'Regent Street',
    'Lombard Street',
    'Canal Street',
    'Kurfürstendamm',
    'Paseo de la Reforma',
    'Avenue des Champs-Élysées',
    'Gran Vía',
    'Nevsky Prospect',
    'Kärntner Straße',
    'Via del Corso',
    'La Rambla',
    'Nanjing Road',
    'Shibuya Crossing',
    'Orchard Road',
    'Rua Augusta',
    'Avenida Paulista',
    'Karl Johans gate',
    'Grafton Street',
    'Vaci Street',
    'Calle Florida',
    'Via Monte Napoleone',
    'Knez Mihailova Street',
    'Strøget',
    'Graben',
    'Friedrichstrasse',
    'Istiklal Avenue',
    'Kingsway',
    'Via Veneto',
    'Kauppatori',
    'Kunming Street',
    'Östgötagatan',
    'Laugavegur',
    'Nikolskaya Street',
    'Avenida Central',
    'Rua de Santa Catarina',
    'İstiklal Caddesi',
    'Vörösmarty Square',
    'Zhongshan Road',
    'Flinders Street',
    'Drottninggatan',
    'Kärntner Strasse',
    'Myeongdong Street',
    'Strøget',
    'Liberdade Avenue',
    'Bourke Street',
    'Abbey Street',
    'Rue de la Paix',
    'Via Condotti',
    'Jiefangbei Street',
    'Princes Street',
    'Khao San Road',
    'Changan Avenue',
    'Pushkinskaya Street',
    'Aoyama Dori',
    'Esplanadi',
    'Amsterdamsestraatweg',
    'Gulou Street',
    'Rua do Ouvidor',
    'Piotrkowska Street',
    'Laugavegur',
    'Calle de Preciados',
    'Rua das Pedras',
    'Stroget',
    'Koningsallee',
    'Kärntner Ring',
    'Ferhadija Street',
    'Strada Lipscani',
    'Drottninggatan',
    'Rua da Prata',
    'Plaza Mayor',
    'Rua de Santa Maria',
    'Avenida da Liberdade',
    'Knez Mihailova',
    'Stradun',
    'Kärntner Strasse',
    'Maidan Nezalezhnosti',
    'Knez Mihailova',
    'La Rambla',
    'Königsallee',
    'Rua do Almada',
    'Knez Mihailova',
    'Knez Mihailova',
    'La Rambla',
    'Graben',
    'Strøget'
  ];
  const companyNames = [
    'Skyward Technologies',
    'VisionEdge Solutions',
    'Pinnacle Innovations',
    'AlphaOmega Industries',
    'Strategic Nexus Corp',
    'InnoVantage Enterprises',
    'Apex Dynamics Inc',
    'TechForge Solutions',
    'Elemental Innovations',
    'ElevateX Systems',
    'Proxima Innovations',
    'Acceleron Enterprises',
    'Synergetic Solutions',
    'NexGen Innovations',
    'OmegaPrime Industries',
    'Vanguard Ventures',
    'SummitPeak Technologies',
    'OrbitEdge Systems',
    'HorizonIQ Corporation',
    'United Innovations Group',
    'Veritas Enterprises',
    'TruEdge Solutions',
    'InnovaSphere Technologies',
    'AscendX Corporation',
    'OmniVista Solutions',
    'Pantheon Innovations',
    'FutureFrontier Corp',
    'Eclipse Dynamics',
    'CentoriaIT Corp',
    'NovaHorizon Technologies',
    'IntelliCore Solutions',
    'ApexGrowth Ventures',
    'Synthetix Innovations',
    'Maximus Enterprises',
    'TechVisionary Corp',
    'Innovatech Solutions',
    'NextEdge Dynamics',
    'Progenix Technologies',
    'AlphaCore Innovations',
    'Genesis Enterprises',
    'Stratagem Solutions',
    'Optimal Innovations',
    'PrimeAxis Technologies',
    'Innovatech Industries',
    'ApexStrive Solutions',
    'VirtuoTech Enterprises',
    'FutureFocus Corp',
    'Synergex Innovations',
    'EvolvEdge Systems',
    'QuantumLeap Ventures',
    'EliteVision Technologies',
    'PioneerEdge Solutions',
    'FrontierWorks Corp',
    'TechNova Innovations',
    'InnoCore Enterprises',
    'Vertigo Dynamics',
    'NexaSphere Technologies',
    'MetaCore Solutions',
    'ApexVista Innovations',
    'Strategix Enterprises',
    'ElevateTech Corp',
    'Syntropy Innovations',
    'ForwardEdge Systems',
    'InnoVise Technologies',
    'NexaCore Solutions',
    'Frontline Innovations',
    'TechMatrix Enterprises',
    'Synergetix Dynamics',
    'OmegaPoint Technologies',
    'Visionary Edge Corp',
    'HorizonTech Solutions',
    'ApexInnovate Ventures',
    'Innovexa Enterprises',
    'AlphaInnovate Corp',
    'ElevonEdge Solutions',
    'MaxTech Innovations',
    'OptimaSphere Technologies',
    'StriveEdge Enterprises',
    'QuantumSynergy Corp',
    'FutureCore Innovations',
    'VertexTech Solutions',
    'InnoLink Dynamics',
    'VistaEdge Technologies',
    'SynergyInno Enterprises',
    'TechFrontier Corp',
    'PioneerTech Innovations',
    'NexGenEdge Solutions',
    'StrategicCore Dynamics',
    'HorizonTech Ventures',
    'InnovaScope Technologies',
    'NexaVision Enterprises',
    'FrontierTech Innovations',
    'EvoCore Solutions',
    'OptimalEdge Enterprises',
    'AlphaNova Technologies',
    'Synthetix Innovations'
  ];
module.exports = {
  countries,
  citiesArrays,
  namesArray,
  lastNames,
  jobs,
  productsArray,
  streets,
  companyNames,
};
